version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:80"

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/Users/zhangwenning/study/docker-node-test/data/db
      - mongodb_config:/Users/zhangwenning/study/docker-node-test/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config